version: '2'

services:
  redis1:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'

  mongodb1:
    image: 'mongo:5.0-focal'
    ports:
      - '27018:27017'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

  mongodb2:
    image: 'mongo:5.0-focal'
    ports:
      - '27019:27017'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    ports:
      - '27020:27017'
    depends_on:
        - mongodb1

  go-svc:
    build: ./backend
    environment:
      - PORT=8000
      - REDIS_ADDRESS=redis1:6379
      - REDIS_SENTINEL_ADDRESSES=
      - REDIS_MASTER_NAME=
      - MONGODB_CONN_URL=mongodb://mongodb1:27017,mongodb://mongodb2:27017,mongodb://mongosetup:27017
    ports:
      - '8000:8000'
    depends_on:
      - redis1

  statics:
    build: ./frontend
    depends_on:
      - go-svc
    ports:
      - '4200:80'
