version: '2'

networks:
  app-net:
    driver: bridge

services:
  redis1:
    image: redis:6.2.6-alpine
    networks:
      - app-net

  redis2:
    image: redis:6.2.6-alpine
    command: redis-server --slaveof redis1 6379
    networks:
      - app-net

  redis-sentinel1:
    build: 
      context: ./redis-sentinel-setup
    depends_on:
      - redis1
      - redis2
    networks:
      - app-net
  
  redis-sentinel2:
    build: 
      context: ./redis-sentinel-setup
    depends_on:
      - redis1
      - redis2
    networks:
      - app-net

  redis-sentinel3:
    build: 
      context: ./redis-sentinel-setup
    depends_on:
      - redis1
      - redis2
    networks:
      - app-net

  mongodb1:
    image: 'mongo:5.0-focal'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    networks:
      - app-net

  mongodb2:
    image: 'mongo:5.0-focal'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    networks:
      - app-net

  mongodb3:
    image: 'mongo:5.0-focal'
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    networks:
      - app-net

  mongodb-configer:
    build: "./mongo-setup"
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - app-net

  backend1:
    build: ./backend
    environment:
      - PORT=8000
      - REDIS_ADDRESS=redis1:6379
      - REDIS_SENTINEL_ADDRESSES=redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      - REDIS_MASTER_NAME=redismaster
      - MONGODB_CONN_URL=mongodb://mongodb1:27017,mongodb://mongodb2:27017,mongodb://mongodb3:27017
    depends_on:
      - redis-sentinel1
      - mongodb-configer
    networks:
      - app-net

  backend2:
    build: ./backend
    environment:
      - PORT=8000
      - REDIS_ADDRESS=redis1:6379
      - REDIS_SENTINEL_ADDRESSES=redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      - REDIS_MASTER_NAME=redismaster
      - MONGODB_CONN_URL=mongodb://mongodb1:27017,mongodb://mongodb2:27017,mongodb://mongodb3:27017
    depends_on:
      - redis-sentinel1
      - mongodb-configer
    networks:
      - app-net
  
  backend3:
    build: ./backend
    environment:
      - PORT=8000
      - REDIS_ADDRESS=redis1:6379
      - REDIS_SENTINEL_ADDRESSES=redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      - REDIS_MASTER_NAME=redismaster
      - MONGODB_CONN_URL=mongodb://mongodb1:27017,mongodb://mongodb2:27017,mongodb://mongodb3:27017
    depends_on:
      - redis-sentinel1
      - mongodb-configer
    networks:
      - app-net

  load-balancer:
    build: ./load-balancer
    depends_on:
      - backend1
      - backend2
      - backend3
    ports:
      - '8000:80'
    networks:
      - app-net

  statics:
    build:
      context: ./frontend
      dockerfile: Dockerfile_deploy
    depends_on:
      - load-balancer
    ports:
      - '4000:80'
    networks:
      - app-net
