FROM redis:6.2.6-alpine

RUN mkdir -p /redis

WORKDIR /redis

COPY sentinel-slave.conf .
COPY entrypoint-slave.sh /usr/local/bin/

RUN chown redis:redis /redis/* && \
    chmod +x /usr/local/bin/entrypoint-slave.sh

ENTRYPOINT ["entrypoint-slave.sh"]