// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/harunalfat/chirpbird/backend/adapters/persistence/redis"
	"github.com/harunalfat/chirpbird/backend/adapters/web"
	"github.com/harunalfat/chirpbird/backend/adapters/web/controllers"
	"github.com/harunalfat/chirpbird/backend/adapters/web/controllers/implementation/gobwas"
)

// Injectors from wire.go:

func Initialize() (*web.WebServer, error) {
	clusterClient, err := redis.NewRedisClusterClient()
	if err != nil {
		return nil, err
	}
	channelRepository := redis.NewRedisChannelRepository(clusterClient)
	handler := gobwas.NewGobwasHandler(channelRepository)
	wsService := gobwas.NewGobwasWSService(handler)
	wsServer := controllers.NewWSServer(wsService)
	webServer := web.NewWebServer(wsServer)
	return webServer, nil
}
