// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/harunalfat/chirpbird/backend/presentation/persistence/implementations/mongodb"
	"github.com/harunalfat/chirpbird/backend/presentation/web/handlers"
	"github.com/harunalfat/chirpbird/backend/use_cases/implementations"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	client, err := mongodb.NewMongoClient()
	if err != nil {
		return nil, err
	}
	channelRepository := mongodb.NewMongodbChannelRepository(client)
	messageRepository := mongodb.NewMongodbMessageRepository(client)
	messageUseCase := implementations.NewMessageUseCaseImpl(messageRepository)
	channelUseCase := implementations.NewChannelUseCaseImpl(channelRepository, messageUseCase)
	node, err := handlers.NewCentrifugeNode()
	if err != nil {
		return nil, err
	}
	nodeWrapper := implementations.NewNodeWrapperImpl(node)
	userRepository := mongodb.NewMongodbUserRepository(client)
	userUseCase := implementations.NewUserUseCaseImpl(channelUseCase, nodeWrapper, userRepository)
	restHandler := handlers.NewRestHandlerImpl(channelUseCase, userUseCase)
	wsHandler := handlers.NewCentrifugeHandler(channelUseCase, node, userUseCase)
	app := &App{
		restHandler: restHandler,
		wsHandler:   wsHandler,
	}
	return app, nil
}
