// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/harunalfat/chirpbird/backend/presentation/persistence"
	"github.com/harunalfat/chirpbird/backend/presentation/web/handlers"
	"github.com/harunalfat/chirpbird/backend/use_cases"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	client, err := persistence.NewMongoClient()
	if err != nil {
		return nil, err
	}
	channelRepository := persistence.NewMongodbChannelRepository(client)
	messageRepository := persistence.NewMongodbMessageRepository(client)
	messageUseCase := usecases.NewMessageUseCase(messageRepository)
	channelUseCase := usecases.NewChannelUseCase(channelRepository, messageUseCase)
	node, err := handlers.NewCentrifugeNode()
	if err != nil {
		return nil, err
	}
	nodeWrapper := usecases.NewNodeWrapperImpl(node)
	userRepository := persistence.NewMongodbUserRepository(client)
	userUseCase := usecases.NewUserUseCase(channelUseCase, nodeWrapper, userRepository)
	restHandler := handlers.NewRestHandler(channelUseCase, userUseCase)
	wsHandler := handlers.NewWSHandler(channelUseCase, node, userUseCase)
	app := &App{
		restHandler: restHandler,
		wsHandler:   wsHandler,
	}
	return app, nil
}
