package env

const (
	MONGODB_CONN_URI         = "MONGODB_CONN_URI"
	PORT                     = "PORT"
	REDIS_ADDRESS            = "REDIS_ADDRESS"
	REDIS_PASSWORD           = "REDIS_PASSWORD"
	REDIS_SENTINEL_ADDRESSES = "REDIS_SENTINEL_ADDRESSES"
	REDIS_MASTER_NAME        = "REDIS_MASTER_NAME"
)
